### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by aeh1707**
- [x] Write unit tests with React Testing Library.
- [x] Write unit tests with snapshots with Jest.

### CODE REVIEW

**Review by t-yanick — CHANGES_REQUESTED** [review]
Hi @aeh1707, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments below and under the review._
#### I will leave this comment here because this concerns files in your repository.
- [x] Your project is missing [package.json ](https://nodejs.org/en/knowledge/getting-started/npm/what-is-the-file-package-json/)file, please kindly add the file and the various dependencies needed to run your tests. Please also ensure all your tests are running before you re-submit for review. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by aeh1707** [comment]
> * [x]  Your project is missing [package.json ](https://nodejs.org/en/knowledge/getting-started/npm/what-is-the-file-package-json/)file, please kindly add the file and the various dependencies needed to run your tests. Please also ensure all your tests are running before you re-submit for review.

@t-yanick It's already there, and we have run the tests, it works just fine I don't get your point.

Capture11

**Comment by t-yanick** [comment]
Hello @aeh1707, please there is a mix up from my end, kindly re-submit the project, the next code reviewer will review it. My sincere apologies for any inconveniences caused.

**Comment by aeh1707** [comment]
> Hello @aeh1707, please there is a mix up from my end, kindly re-submit the project, the next code reviewer will review it. My sincere apologies for any inconveniences caused.

@t-yanick No worry brother, not a big problem.

**Review by DeliceLydia — APPROVED** [review]
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
